src/Entity/LogBookSetup.php
<?php

namespace App\Entity;

use App\Model\OsType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PreFlush;
use Doctrine\ORM\Mapping\PrePersist;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogBookSetupRepository")
 * @ORM\Table(name="lbook_setups")
 * @UniqueEntity("name", message="Setup with this name already exist")
 * @ORM\HasLifecycleCallbacks()
 */
class LogBookSetup
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", options={"unsigned"=true})
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="Test Verdict name cannot ne empty")
     */
    protected $name = '';

    /**
     * @var string
     *
     * @ORM\Column(name="name_shown", type="string", length=50, nullable=true)
     */
    protected $nameShown = '';

    /**
     * @var bool
     *
     * @ORM\Column(name="is_disabled", type="boolean", options={"default" : "0"})
     */
    protected $disabled = false;

    /**
     * @var integer
     *
     * @ORM\Column(name="os", type="smallint", nullable=true)
     */
    protected $os = 0;

    /**
     * @var bool
     *
     * @ORM\Column(name="check_up_time", type="boolean", options={"default" : "0"})
     */
    protected $checkUpTime = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LogBookUser", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="owner", referencedColumnName="id", nullable=true)
     */
    protected $owner = 0;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\LogBookUser", fetch="EXTRA_LAZY")
     */
    protected $moderators;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LogBookCycle", mappedBy="setup", cascade={"all"}, fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="cycles", fieldName="id", referencedColumnName="id")
     * @ORM\OrderBy({"id" = "DESC"})
     */
    protected $cycles;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_private", type="boolean", options={"default"=false})
     */
    protected $isPrivate = false;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     * //@Assert\DateTime()
     */
    protected $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true, options={"default"="CURRENT_TIMESTAMP"})
     * //@Assert\DateTime()
     */
    protected $updatedAt;

    public static $MAX_NAME_LEN = 250;

    /**
     * LogBookSetup constructor.
     */
    public function __construct()
    {
        $this->setUpdatedAt();
        $this->setCreatedAt();
        $this->moderators = new ArrayCollection();
        $this->cycles = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param mixed $owner
     */
    public function setOwner($owner): void
    {
        $this->owner = $owner;
    }

    /**
     * @return bool
     */
    public function isPrivate(): bool
    {
        return $this->isPrivate;
    }

    /**
     * @param bool $isPrivate
     */
    public function setIsPrivate(bool $isPrivate): void
    {
        $this->isPrivate = $isPrivate;
    }

    /**
     * @return Collection|LogBookUser[]
     */
    public function getModerators(): Collection
    {
        return $this->moderators;
    }

    /**
     * @param Collection $moderators
     */
    public function setModerators(Collection $moderators): void
    {
        $this->moderators = $moderators;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    public static function validateName($newName): string
    {
        if (mb_strlen($newName) > self::$MAX_NAME_LEN) {
            $newName = mb_substr($newName, 0, self::$MAX_NAME_LEN);
        }
        return $newName;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = self::validateName($name);
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    /**
     * @return string
     */
    public function getNameShown(): ?string
    {
        if (\strlen($this->nameShown)>0) {
            return $this->nameShown;
        }

        return $this->getName();
    }

    /**
     * @param string $nameShown
     */
    public function setNameShown(string $nameShown=null): void
    {
        $this->nameShown = $nameShown;
    }

    /**
     * @return bool
     */
    public function isDisabled(): bool
    {
        return $this->disabled;
    }

    /**
     * @param bool $disabled
     */
    public function setDisabled(bool $disabled): void
    {
        $this->disabled = $disabled;
    }

    /**
     * @return mixed
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * @return string
     */
    public function getOsStr(): string
    {
        return OsType::getTypeName($this->getOs());
    }

    /**
     * @param $os
     */
    public function setOs($os): void
    {
        $this->os = $os;
    }

    /**
     * @return bool
     */
    public function isCheckUpTime(): bool
    {
        return $this->checkUpTime;
    }

    /**
     * @param bool $checkUpTime
     */
    public function setCheckUpTime(bool $checkUpTime): void
    {
        $this->checkUpTime = $checkUpTime;
    }

    /**
     * @return Collection|LogBookCycle[]
     */
    public function getCycles(): Collection
    {
        return $this->cycles;
    }

    /**
     * @param Collection $cycles
     */
    public function setCycles($cycles): void
    {
        $this->cycles = $cycles;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @PrePersist
     */
    public function setCreatedAt(): void
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @PreFlush
     * @PrePersist
     */
    public function setUpdatedAt(): void
    {
        $this->updatedAt = new \DateTime();
    }
}

templates/lbook/setup/edit.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Setup edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}
    <div class="well well-lg">
        <h4 class="green smaller lighter">Options</h4>
        <ul class="list-inline">
            <li>
                <i class="ace-icon fa fa-share green bigger-110"></i>
                <a href="{{ path('setup_show', { 'id': setup.id }) }}">Back to Setup</a>
            </li>
            <li>
                <a href="{{ path('setup_index') }}">Back to the list</a>
            </li>
            {% if is_granted('delete', setup) %}
                {% if delete_form is not null %}
                    <li>
                        {{ form_start(delete_form) }}
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure about delete this setup?')">
                        {{ form_end(delete_form) }}
                    </li>
                {%  endif %}
            {%  endif %}
        </ul>
    </div>

{% endblock %}

templates/lbook/setup/index.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LBOOK Setup list{% endblock %}
{% block content %}
    <h1>Setup list</h1>
    <div>Count : {{ size }}</div>
    {% include "lbook/search.html.twig" %}
    {% set pagePath = "setup_index" %}
    {% include "lbook/paginator.html.twig" %}
    <table class="records_list table table-striped table-condensed table-hover" data-classes="table table-no-bordered"
           data-pagination="true" data-toggle="table"
           data-page-size="50" data-page-list="[5, 10, 20, 50]" data-sort-order="desc">
        <thead>
        <tr>
            <th data-sortable="true" title="Updated image" class="time_diff_icon">&nbsp;</th>
            <th data-sorter="htmlSorter" data-sortable="true">ID</th>
            <th data-sorter="htmlSorter" data-sortable="true" title="Full setup name">Name</th>
            <th data-sortable="true" title="Cycles found">Cycles</th>
            <th data-sortable="true" title="Friendly short setup name">Short Name</th>
            <th data-sortable="true">OS</th>
            <th data-sortable="true" title="Owner Name">Owner</th>
            <th data-sorter="dataTitleDateSorter" data-sortable="true" title="Update time">Updated</th>
            <th data-sortable="true" title="Check Uptime">UPT</th>
            <th data-sortable="true" title="Moderators cound">Moderators</th>
            <th data-sortable="true" title="Shows if the setup is disabled">Disabled</th>
            <th class="setup_list_options_column">Options</th>
        </tr>
        </thead>
        <tbody class="searchable">
        {% set break = false %}
        {% set counter = 0 %}
        {% for setup in iterator if not break %}
        {% if counter == 10000 %}
            {% set break = true %}
        {% endif %}
        {% set counter = counter+1 %}
            <tr>
                <td>
                    {%  if date(setup.updatedAt) > date('-20minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o pink smaller-90" title="Updated {{ setup.updatedAt|time_diff }}"></i>
                    {% endif %}
                </td>
                <td><a href="{{ path('setup_show_first', { 'id': setup.id }) }}">{{ setup.id }}</a></td>
                <td><a href="{{ path('setup_show_first', { 'id': setup.id }) }}">{{ setup.name }}</a></td>
                <td>{{ setup.cycles | length }}</td>
                <td>{{ setup.nameShown }}</td>
                <td>{{ setup.osStr }}</td>
                <td>{{ setup.owner }}</td>
                <td><span data-title="{{ setup.updatedAt|date('ymdHis') }}" title="Updated at {{ setup.updatedAt|date('d/m/Y H:i:s') }}">{{ setup.updatedAt|time_diff}}</span></td>
                <td>{{ setup.checkUpTime ? 'Yes':'No' }}</td>
                <td>{{ setup.moderators|length }}</td>
                <td>{{ setup.disabled ? 'Yes':'False' }}</td>
                <td>
                    <div class="hidden-sm hidden-xs action-buttons">
                        <a class="blue" href="{{ path('setup_show', { 'id': setup.id }) }}" title="Show">
                            <i class="ace-icon fa fa-search-plus bigger-130"></i>
                        </a>
                        {% if is_granted('edit', setup) %}
                        <a class="green" href="{{ path('setup_edit', { 'id': setup.id }) }}" title="Edit">
                            <i class="ace-icon fa fa-pencil bigger-130"></i>
                        </a>
                        {% endif %}
                        {#<a class="red" href="#" title="Delete">#}
                            {#<i class="ace-icon fa fa-trash-o bigger-130"></i>#}
                        {#</a>#}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('setup_new') }}">Create a new setup</a>
        </li>
    </ul>
{% endblock %}

templates/lbook/setup/new.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Setup creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('setup_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}

templates/lbook/setup/show.full.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LBOOK Setup [{{ setup.id }}:{{ setup.name }}] {% endblock %}
{% block content %}
    <h3>Setup [{{ setup.id }}] : {{ setup.name }}</h3>
    <table class="records_list table table-striped table-condensed">
        <tbody>
        {#<tr>#}
        {#<th>Id</th>#}
        {#<td>{{ setup.id }}</td>#}
        {#</tr>#}
        <tr>
            <th>OS</th>
            <td><span class="label label-lg label-yellow">{{ setup.osStr }}</span></td>
        </tr>
        {#<tr>#}
        {#<th>Name</th>#}
        {#<td>{{ setup.name }}</td>#}
        {#</tr>#}
        <tr>
            <th>Short Name</th>
            <td>
                <i class="ace-icon fa fa-bookmark"></i>
                {{ setup.nameShown }}
            </td>
        </tr>
        <tr>
            <th>Disabled / Visibility / Check Uptime</th>
            <td>
                <span class="blue">
                {{ setup.disabled ? '<i class="ace-icon fa fa-lock"></i> Yes':'<i class="ace-icon fa fa-unlock"></i> False' }}
                </span>
                /
                <span class="green">
                {{ setup.private ? '<i class="ace-icon fa fa-eye"></i> Private':'<i class="ace-icon fa fa-globe"></i> Public' }}
                </span>
                /
                <span class="yellow">
                {{ setup.checkUpTime ? '<i class="ace-icon fa fa-check-square-o"></i> Yes':'<i class="ace-icon fa fa-ban"></i> No' }}
                </span>
            </td>
        </tr>
        <tr>
            <th>Created / Updated</th>
            <td>
                <i class="ace-icon fa fa-calendar"></i>
                <span class="blue">
                    {{ setup.createdAt|date('d/m/Y H:i:s') }}
                </span>
                /
                <i class="ace-icon fa fa-calendar"></i>
                <span class="blue">
                {{ setup.updatedAt|date('d/m/Y H:i:s') }}
                </span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <i class="ace-icon fa fa-info-circle"></i>
                {%  if date(setup.updatedAt) > date('-20minutes') %}
                    {% set updatedClass="red" %}
                {% else %}
                    {% set updatedClass="blue" %}
                {% endif %}
                <span class="{{ updatedClass }}">
                {{ setup.updatedAt|time_diff}}
                </span>
            </td>
        </tr>
        <tr>
            <th>Owner / Moderators</th>
            <td>
                <i class="ace-icon fa fa-key"></i>
                <span class="label label-sm label-success label-white arrowed arrowed-right">{{ setup.owner}}</span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <i class="ace-icon fa fa-users"></i>
                {% for moderator in setup.moderators %}
                    <a href="{{ path('user_show', { 'id': moderator.id }) }}" target="_blank">
                        {% if moderator.id == setup.owner.id %}
                            <span class="label label-sm label-danger label-white arrowed arrowed-right" title="Setup owner">{{ moderator.username }}</span>
                        {% else %}
                            <span class="label label-sm label-primary label-white arrowed arrowed-right">{{ moderator.username }}</span>
                        {% endif %}
                    </a>
                {% endfor %}
            </td>
        </tr>
        {% set already_printed = ['moderators', 'id', 'name', 'cycles', 'nameShown', 'createdAt', 'updatedAt', 'owner', 'disabled', 'os', 'isPrivate', 'checkUpTime'] %}
        {% for key, value in setup|cast_to_array %}
            {% if key not in already_printed%}
                <tr>
                    <th>{{ key | capitalize}}</th>
                    <td>{{ value }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    {% set pagePath = "setup_show" %}
    {% set objId = setup.id %}
    {% include "lbook/double.paginator.html.twig" %}
    {%  set cycles = setup.cycles %}
    <div>Count : {{ size }}</div>
    {% include "lbook/search.html.twig" %}
    <table class="records_list table table-striped table-condensed table-hover" data-classes="table table-no-bordered"
           data-pagination="true" data-search="true" data-toggle="table"
           data-page-size="100" data-page-list="[20, 50, 100, 'ALL']" data-sort-order="desc">
        <thead>
        <tr>
            <th data-sortable="true" title="Updated image" class="time_diff_icon">&nbsp;</th>
            <th data-sorter="htmlSorter" data-sortable="true">Id</th>
            <th data-sorter="htmlSorter" data-sortable="true" class="setup_cycle_name_column">Name</th>
            <th data-sortable="true">Tests</th>
            <th data-sortable="true">Build</th>
            <th data-sorter="htmlSorter" data-sortable="true">Pass Rate</th>
            <th data-sortable="true">Controller</th>
            <th data-sortable="true">DUT</th>
            <th data-sortable="true">Uploader</th>
            <th data-sortable="true">Period</th>
            <th data-sortable="true">Test time</th>
            <th data-sorter="htmlSorter" data-sortable="true">Updated</th>
            <th class="setup_cycle_options_column">Options</th>
        </tr>
        </thead>
        <tbody class="searchable">
        {% set break = false %}
        {% set counter = 0 %}
        {% for cycle in iterator if not break %}
            {% if counter == 10000 %}
                {% set break = true %}
            {% endif %}
            {% set counter = counter+1 %}
            <tr>
                <td>
                    {% if date(cycle.updatedAt) > date('-60minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o pink smaller-90" title="Updated {{ cycle.updatedAt|time_diff }}"></i>
                    {% endif %}
                </td>
                <td><a href="{{ path('cycle_show_first', { 'id': cycle.id }) }}">{{ cycle.id }}</a></td>
                <td title="{{ cycle.name }}"><a href="{{ path('cycle_show_first', { 'id': cycle.id }) }}">{{ shortString(cycle.name, 35, "...") }}</a></td>
                <td>{{ cycle.testsCount }}</td>
                <td title="{{ cycle.build }}">{{ shortString(cycle.build, 30) }}</td>
                <td><span class="{{ passRateToColor(cycle.passRate) }}">{{ cycle.passRate }}%</span></td>
                <td>{{ cycle.controller }}</td>
                <td>{{ cycle.dut }}</td>
                <td>{{ cycle.targetUploader }}</td>
                <td>{{ cycle.period |  ExecutionTimeGeneric}}</td>
                <td>{{ cycle.testsTimeSum |  ExecutionTimeGeneric}}</td>
                <td>
                    <span title="Updated [{{ cycle.updatedAt |date('d/m/Y H:i:s') }}] {{ cycle.updatedAt|time_diff }}">
                        {{ cycle.updatedAt |date('d/m H:i:s') }}
                    </span>
                </td>
                <td>
                    <div class="hidden-sm hidden-xs action-buttons">
                        <a class="blue" href="{{ path('cycle_show', { 'id': cycle.id }) }}" title="Show">
                            <i class="ace-icon fa fa-search-plus bigger-130"></i>
                        </a>
                        {% if is_granted('edit', setup) %}
                            <a class="green" href="{{ path('cycle_edit', { 'id': cycle.id }) }}" title="Edit">
                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                            </a>
                        {% endif %}
                        {#<a class="red" href="#" title="Delete">#}
                        {#<i class="ace-icon fa fa-trash-o bigger-130"></i>#}
                        {#</a>#}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('setup_index') }}">Back to the list</a>
        </li>
        {% if is_granted('edit', setup) %}
            <li><a href="{{ path('setup_edit', { 'id': setup.id }) }}">Edit</a></li>
        {% endif %}
        {#{% if is_granted('delete', setup) %}#}
        {#<li>#}
        {#{{ form_start(delete_form) }}#}
        {#<input type="submit" value="Delete" onclick="return confirm('Are you sure about delete this setup?')">#}
        {#{{ form_end(delete_form) }}#}
        {#</li>#}
        {#{% endif %}#}
    </ul>
{% endblock %}

templates/lbook/setup/show.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LBOOK Setup [{{ setup.id }}:{{ setup.name }}] {% endblock %}
{% block content %}
    <h1>Setup [{{ setup.id }}] : {{ setup.name }}</h1>
    <table class="records_list table table-striped table-condensed">
        <tbody>
            {#<tr>#}
                {#<th>Id</th>#}
                {#<td>{{ setup.id }}</td>#}
            {#</tr>#}
            <tr>
                <th>OS</th>
                <td><span class="label label-lg label-yellow">{{ setup.osStr }}</span></td>
            </tr>
            {#<tr>#}
                {#<th>Name</th>#}
                {#<td>{{ setup.name }}</td>#}
            {#</tr>#}
            <tr>
                <th>Short Name</th>
                <td>{{ setup.nameShown }}</td>
            </tr>
            <tr>
                <th>Disabled</th>
                <td>
                    {{ setup.disabled ? 'Yes':'False' }}
                </td>
            </tr>
            <tr>
                <th>Created </th>
                <td>
                    <i class="ace-icon fa fa-calendar"></i>
                    {{ setup.createdAt|date('d/m/Y H:i:s') }}
                </td>
            </tr>
            <tr>
                <th>Updated</th>
                <td>
                    <i class="ace-icon fa fa-calendar"></i>
                    {{ setup.updatedAt|date('d/m/Y H:i:s') }}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="ace-icon fa fa-info-circle"></i>
                    {{ setup.updatedAt|time_diff}}
                </td>
            </tr>
            <tr>
                <th>Owner/Moderators</th>
                <td>
                    <i class="ace-icon fa fa-key"></i>
                    <span class="label label-sm label-success label-white arrowed arrowed-right">{{ setup.owner}}</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="ace-icon fa fa-users"></i>
                    {% for moderator in setup.moderators %}
                        <a href="{{ path('user_show', { 'id': moderator.id }) }}" target="_blank">
                            {% if moderator.id == setup.owner.id %}
                            <span class="label label-sm label-danger label-white arrowed arrowed-right" title="Setup owner">{{ moderator.username }}</span>
                            {% else %}
                            <span class="label label-sm label-primary label-white arrowed arrowed-right">{{ moderator.username }}</span>
                            {% endif %}
                        </a>
                    {% endfor %}
                </td>
            </tr>
            {% set already_printed = ['moderators', 'id', 'name', 'cycles', 'nameShown', 'createdAt', 'updatedAt', 'owner', 'disabled', 'os'] %}
            {% for key, value in setup|cast_to_array %}
                {% if key not in already_printed%}
                    <tr>
                        <th>{{ key | capitalize}}</th>
                        <td>{{ value }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    {%  set cycles = setup.cycles %}
    {% include "lbook/search.html.twig" %}
    <table class="records_list table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th></th>
            <th>Id</th>
            <th>Name</th>
            <th>Tests</th>
            <th>Build</th>
            <th>Pass Rate</th>
            <th>Controller</th>
            <th>DUT</th>
            <th>Uploader</th>
            <th>Period</th>
            <th>Test time</th>
            <th>Updated</th>
            <th>Options</th>
        </tr>
        </thead>
        <tbody class="searchable">
        {% for cycle in cycles %}
            <tr>
                <td>
                    {%  if date(cycle.updatedAt) > date('-60minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o pink bigger-130" title="Updated {{ cycle.updatedAt|time_diff }}"></i>
                    {% endif %}
                </td>
                <td><a href="{{ path('cycle_show', { 'id': cycle.id }) }}">{{ cycle.id }}</a></td>
                <td><a href="{{ path('cycle_show', { 'id': cycle.id }) }}">{{ cycle.name }}</a></td>
                <td>{{ cycle.tests | length }}</td>
                <td>{{ cycle.build }}</td>
                <td>{{ cycle.passRate }}%</td>
                <td>{{ cycle.controller }}</td>
                <td>{{ cycle.dut }}</td>
                <td>{{ cycle.targetUploader }}</td>
                <td>{{ cycle.period |  ExecutionTimeGeneric}}</td>
                <td>{{ cycle.testsTimeSum |  ExecutionTimeGeneric}}</td>
                <td><span title="Updated [{{ cycle.updatedAt |date('d/m/Y H:i:s') }}] {{ cycle.updatedAt|time_diff }}">{{ cycle.updatedAt |date('d/m H:i:s') }}</span></td>
                <td>
                    <a href="{{ path('cycle_show', { 'id': cycle.id }) }}">show</a>
                    {% if is_granted('edit', setup) %}
                    <a href="{{ path('cycle_edit', { 'id': cycle.id }) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('setup_index') }}">Back to the list</a>
        </li>
        {% if is_granted('edit', setup) %}
        <li><a href="{{ path('setup_edit', { 'id': setup.id }) }}">Edit</a></li>
        {% endif %}
        {#{% if is_granted('delete', setup) %}#}
        {#<li>#}
            {#{{ form_start(delete_form) }}#}
                {#<input type="submit" value="Delete" onclick="return confirm('Are you sure about delete this setup?')">#}
            {#{{ form_end(delete_form) }}#}
        {#</li>#}
        {#{% endif %}#}
    </ul>
{% endblock %}